---
title: "RL teaching site"
permalink: /
---

theme: minima

minima:
  nav:
    enabled: false  # Cela d√©sactive le menu de navigation qui affiche les liens vers toutes les pages.

head:
  - "<!-- Google tag (gtag.js) -->"
  - "<script async src='https://www.googletagmanager.com/gtag/js?id=G-ZPLLS1XZC8'></script>"
  - "<script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-ZPLLS1XZC8');
    </script>"
